# 파일 리스트를 csv로 변환하기

In [26]:
import numpy as np
import pandas as pd
from glob import glob

In [27]:
total = glob('dataset/*/*/*')
train = glob('dataset/train/*/*')
test = glob('dataset/test/*/*')
val = glob('dataset/val/*/*')

len(total), len(train), len(test), len(val)

(136, 84, 40, 12)

In [33]:
splitted_arr = []
for t in train:
    splited = t.split('\\')
    splited = splited[1:]
    splitted_arr.append(splited)

train_df = pd.DataFrame(data=splitted_arr, columns=['case','filename'])

train_df

        case           filename
0   accident   accident_000.mp4
1   accident   accident_001.mp4
2   accident  accident_0010.mp4
3   accident  accident_0011.mp4
4   accident  accident_0012.mp4
..       ...                ...
79   driving   driving_0019.mp4
80   driving    driving_002.mp4
81   driving   driving_0020.mp4
82   driving   driving_0021.mp4
83   driving   driving_0022.mp4

[84 rows x 2 columns]

In [30]:
splitted_arr = []
for t in test:
    splited = t.split('\\')
    splited = splited[1:]
    splitted_arr.append(splited)

test_df = pd.DataFrame(data=splitted_arr, columns=['case','filename'])

test_df

        case           filename
0   accident  accident_0052.mp4
1   accident  accident_0053.mp4
2   accident  accident_0054.mp4
3   accident  accident_0055.mp4
4   accident  accident_0056.mp4
5   accident  accident_0057.mp4
6   accident  accident_0058.mp4
7   accident  accident_0059.mp4
8   accident   accident_006.mp4
9   accident  accident_0060.mp4
10  accident  accident_0061.mp4
11  accident  accident_0062.mp4
12  accident  accident_0063.mp4
13  accident  accident_0064.mp4
14  accident  accident_0065.mp4
15  accident  accident_0066.mp4
16  accident  accident_0067.mp4
17  accident   accident_007.mp4
18  accident   accident_008.mp4
19  accident   accident_009.mp4
20   driving   driving_0029.mp4
21   driving    driving_003.mp4
22   driving   driving_0030.mp4
23   driving   driving_0031.mp4
24   driving   driving_0032.mp4
25   driving   driving_0033.mp4
26   driving   driving_0034.mp4
27   driving   driving_0035.mp4
28   driving   driving_0036.mp4
29   driving   driving_0037.mp4
30   driving   driving_0038.mp4
31   driving   driving_0039.mp4
32   driving    driving_004.mp4
33   driving   driving_0040.mp4
34   driving   driving_0041.mp4
35   driving    driving_005.mp4
36   driving    driving_006.mp4
37   driving    driving_007.mp4
38   driving    driving_008.mp4
39   driving    driving_009.mp4

In [31]:
splitted_arr = []
for t in val:
    splited = t.split('\\')
    splited = splited[1:]
    splitted_arr.append(splited)

val_df = pd.DataFrame(data=splitted_arr, columns=['case','filename'])

val_df

        case           filename
0   accident  accident_0047.mp4
1   accident  accident_0048.mp4
2   accident  accident_0049.mp4
3   accident   accident_005.mp4
4   accident  accident_0050.mp4
5   accident  accident_0051.mp4
6    driving   driving_0023.mp4
7    driving   driving_0024.mp4
8    driving   driving_0025.mp4
9    driving   driving_0026.mp4
10   driving   driving_0027.mp4
11   driving   driving_0028.mp4

In [34]:
len(train_df), len(test_df), len(val_df)

(84, 40, 12)

In [35]:
train_df.to_csv('train.csv', index=True)
test_df.to_csv('test.csv', index=True)
val_df.to_csv('val.csv', index=True)